### ISSUE TITLE
Have the packet arrays at the same location in the parsed results (load output) as in the VariableLength packet definition

### ISSUE THREAD

**Issue by tloubrieu-jpl** [CCSDSPy/ccsdspy#106]
As for now, at the output of function `_unexpand_field_arrays` they are pushed at the end of the list of fields, instead of where they were origninally defined.

This is a minor request, but if possible, that would help the user to retrieve the parsed data where it was initially defined.

**Comment by ddasilva** [comment]
Thanks @tloubrieu-jpl! Just to be clear, by "same location" you are referring to the order in which the keys iterate in the returned dict?

**Comment by tloubrieu-jpl** [comment]
Hi @ddasilva , yes, the fieldsArrays are found at the end of the keys of the dictionary returned by the load() method, wherever they were in the VariableLength object init.
