### ISSUE TITLE
Europa-Clipper Science Data System uses CCSDSpy

### ISSUE THREAD

**Issue by tloubrieu-jpl** [CCSDSPy/ccsdspy#121]
We now do use ccsdspy for our production parsing of the CCSDS packets.
Here is the logo of the mission:

![image](https://github.com/CCSDSPy/ccsdspy/assets/60993872/4420fc85-ce93-4f37-8ed2-bb58ecac61a8)

**Comment by tloubrieu-jpl** [comment]
ccsdspy is used by Europa-Clipper through this opensource package https://github.com/nasa/pydownlinkparser/

**Comment by tloubrieu-jpl** [comment]
Hi @ddasilva ,

Sorry for my late reply. I missed that Europa-Clipper was already cited as user. This is indeed the old logo so that would be nice to use the new one. Thanks !

**Comment by ddasilva** [comment]
Image was updated on the readme and home page (if you don't see it try forcing cache reset)

**Comment by tloubrieu-jpl** [comment]
Great ! Thanks @ddasilva
