### ISSUE TITLE
Create a stable release after commit 31f1a33377fc540096722520fa1512a986f8f5b0

### ISSUE THREAD

**Issue by tloubrieu-jpl** [CCSDSPy/ccsdspy#123]
For Europa-clipper we will have a stable release of our Science Data System which has a dependency on ccsdspy which need to be on a stable release as well.

The latest PR that we need in ccsdspy is https://github.com/CCSDSPy/ccsdspy/pull/118

Thanks

**Comment by ddasilva** [comment]
Thanks @tloubrieu-jpl I will get around to it this week

**Comment by tloubrieu-jpl** [comment]
👍

**Comment by ddasilva** [comment]
Hi @tloubrieu-jpl ,

Release v1.3.0 has been added to PyPI:
https://pypi.org/project/ccsdspy/1.3.0/

and the change log has been updated:
https://docs.ccsdspy.org/en/latest/whatsnew/changelog.html
