### ISSUE TITLE
Consider providing a way to cite this package in the scientific literature

### ISSUE THREAD

**Issue by ehsteve** [CCSDSPy/ccsdspy#43]
Scientific packages (e.g. sunpy, scipy) provide a way to cite their use by providing a doi (e.g. [scipy](https://scipy.org/citing-scipy/)). There are many ways to get a doi associated with the package
* zenodo - allows you to get a doi without writing a paper, sunpy does this for every release.
* Journal of Open Source Software ([JOSS](https://joss.theoj.org/) allows you to get a doi by submitting to them a short narrative paper and the package. Your code is actually reviewed before being accepted.
* submitting a paper to an actual journal. Many journals will now accept papers about software tools.

Of course, you do not have to do just one. SunPy has actually done all of them! See [this page](https://docs.sunpy.org/en/stable/about.html).

**Comment by ddasilva** [comment]
I agree, this is something we want to do. We should start with zenodo in the short term, and draft a publication after we implement enough features to say we are one iteration of "complete vision". I think to get to that point we would want to implement support for some common flight software packet definition export formats (like [XTCE](https://public.ccsds.org/Pubs/660x2g2.pdf)) and provide a few more utils like `python -m split_by_apid`.

As far as "actual journals", I don't know where this would fit, maybe in one of the AIAA or IEEE aerospace journals?

**Comment by jmbhughes** [comment]
This is a great idea. We'd love to cite and give you credit in a PUNCH paper. Zenodo is very easy to set up in my experience. You essentially just give it permission to access your GitHub and then select which repo to make a DOI for.

**Comment by ehsteve** [comment]
@ddasilva I would recommend you do it like we do for SunPy. We publish the library and create new DOIs for each release on Zenodo.  See [sunpy|Zenedo](https://zenodo.org/record/7803148#.ZDK4sC-B1pQ). That way users can cite a specific release. For reference here is the [Citing SunPy page](https://sunpy.org/about#acknowledging-or-citing-sunpy).

**Comment by ddasilva** [comment]
I made a zenodo DOI for this. Remaining work for this ticket is to add it to the README and the website:
https://zenodo.org/record/7819991
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7819991.svg)](https://doi.org/10.5281/zenodo.7819991)

**Comment by ehsteve** [comment]
Should this issue be closed? Or do you want to leave it open for discuss other ways to cite like a paper or something?

**Comment by ddasilva** [comment]
Not yet, I want to add a page to the website and the link to the README

**Comment by ddasilva** [comment]
The DOI has been added to the readme and the website. I am closing this issue, feel free to reopen or make a new issue if further discussion is desired
