### ISSUE TITLE
Documentation for CSV File Packet Definition

### ISSUE THREAD

**Issue by ddasilva** [CCSDSPy/ccsdspy#64]
It would be good to have a section in the user guide explaining how to define packet definitions using CSV files. This ticket is to add that section to the user's guide.

**Comment by jmbhughes** [comment]
@ddasilva I was looking for this to see if I could remove some of our custom definition loading code in favor of using the built-in function. I'm happy to write up this documentation from what I can gleam from the code.

**Comment by ddasilva** [comment]
@jmbhughes That would be great! I think this could be a new page on the User's Guide, called "Loading Packet Definitions from a File" or similar.

Let me know if there's anything you need from me.
