### ISSUE TITLE
Add converters to convert segments of bytes to strings in binary, oct, or hex representation

### ISSUE THREAD

**Issue by ddasilva** [CCSDSPy/ccsdspy#73]
This ticket is to support converts that turn segments of bytes into strings in binary, oct, or hex representation. This came out of conversations with @tloubrieu-jpl and @nischayn99 about something that they had in their legacy code for parsing CCSDS packets in Europa Clipper, that would be nice to have built in.

I think the most basic way this could be done would be as follows:

```python
from ccsdspy import FixedLength, converters

pkt = FixedLength([
    PacketArray(
        name='some_bytes',
        data_type='uint',
        bit_length=8,
        array_shape=100,
    ),
])
pkt.add_converted_field(
    "some_bytes", 
    "some_bytes_as_string", 
    converters.StringifyBytes(format="oct")  # or "hex", "bin"
)
result = pkt.load('MyCCSDS.tlm')

print(result['some_bytes_as_string'])
```

Which would print an array of strings in oct format.

**Comment by ddasilva** [comment]
@tloubrieu-jpl Can you confirm the proposed implementation would fit your use case?

**Comment by ddasilva** [comment]
A merge request was open for this, see #75

**Comment by tloubrieu-jpl** [comment]
Thanks @ddasilva , that will fit our need, sorry I missed your comment earlier. I am glad that you moved forward.
