### ISSUE TITLE
Metadata incorrect when trying to install from pip. Instead, pip installs version 0.0.13 and won't install 1.1.1. 

### ISSUE THREAD

**Issue by umer936** [CCSDSPy/ccsdspy#95]
```
root@137a5b971b25:/CoDICE# pip install ccsdspy==1.1.1
Collecting ccsdspy==1.1.1
  Using cached ccsdspy-1.1.1.tar.gz (4.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package ccsdspy produced metadata for project name unknown. Fix your #egg=ccsdspy fragments.
Discarding https://files.pythonhosted.org/packages/0b/32/256d1c20ef299cc449b5b669c9fde531eee9eabaa251abc9ee851ea7a068/ccsdspy-1.1.1.tar.gz#sha256=9682d22101cfc88d46cc2d8a04e25dc29cc5d91a695ea2e640d4764deb9e0f82 (from https://pypi.org/simple/ccsdspy/) (requires-python:>=3.6): Requested unknown from https://files.pythonhosted.org/packages/0b/32/256d1c20ef299cc449b5b669c9fde531eee9eabaa251abc9ee851ea7a068/ccsdspy-1.1.1.tar.gz#sha256=9682d22101cfc88d46cc2d8a04e25dc29cc5d91a695ea2e640d4764deb9e0f82 has inconsistent name: filename has 'ccsdspy', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement ccsdspy==1.1.1 (from versions: 0.0.12_fixed, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.13, 1.0.0, 1.1.0.post1, 1.1.1)
ERROR: No matching distribution found for ccsdspy==1.1.1
```

Metadata incorrect when trying to install from pip. Instead, pip installs version 0.0.13. 
Any of the 1.x versions do the same.

**Comment by ddasilva** [comment]
Hmm what version of pip are you on? this is what I get

```
 λ ~ pip install ccsdspy==1.1.1
Defaulting to user installation because normal site-packages is not writeable
Collecting ccsdspy==1.1.1
  Downloading ccsdspy-1.1.1.tar.gz (4.7 MB)
     |████████████████████████████████| 4.7 MB 1.4 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.8.0 in ./.local/lib/python3.8/site-packages (from ccsdspy==1.1.1) (1.21.0)
Building wheels for collected packages: ccsdspy
  Building wheel for ccsdspy (PEP 517) ... done
  Created wheel for ccsdspy: filename=ccsdspy-1.1.1-py3-none-any.whl size=2606609 sha256=5db9be2d181961ff65df6e6a639d7198a91b7f633c12359272669b94f3d478ea
  Stored in directory: /home/daniel/.cache/pip/wheels/bd/7f/6f/a1eb51f97999b13ac9c7131b261d4d0e7ea21f043665855b63
Successfully built ccsdspy
Installing collected packages: ccsdspy
  Attempting uninstall: ccsdspy
    Found existing installation: ccsdspy 1.0.0
    Uninstalling ccsdspy-1.0.0:
      Successfully uninstalled ccsdspy-1.0.0
Successfully installed ccsdspy-1.1.1
WARNING: You are using pip version 21.1.2; however, version 23.2.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by umer936** [comment]
I was on 22.0.2. 

You're on 21.1.2 so I was skeptical. 

However, upgrading pip to 23.2.1 did just fix it. 
`pip install -U pip`
`pip install ccsdspy==1.1.1` now just worked. 

Didn't have an issue with installing other pip packages so not sure, but it is resolved. 

For reference, I'm in a Docker container running Ubuntu 22.04.3 LTS. 

Thank you for the quick response! :)

**Comment by ddasilva** [comment]
Thanks @umer936, glad we got this sorted out. I'll keep an eye on the package config to see if any other funny behavior happens. 

Do you mind if I ask what you are using CCSDSPy for and where? We like to collect where/what it's being used to prioritize issues and populate our "used by" section.

**Comment by umer936** [comment]
For sure. I'm at SwRI, which is already listed in the description. I'm a software dev currently working on the in-development IMAP / CoDICE. We ingest in spreadsheets of instrument configs and bin files and use your PacketFields, PacketArray, and converters to put the data in a database for plotting. 

I know we use it in other missions but I don't know which ones off-hand. I'll ask someone who knows in a week or so and reply here when I find out. 

Thanks!

**Comment by ddasilva** [comment]
Great to hear! Do you mind if I add IMAP / CoDICE to the used by list? 

Seems you're comfortable making github issues, but I'll just say the same thing to you that I say to everyone: if you run into any problems, or have any thoughts on features that would improve things for your org, feel free to open an issue or discussion thread. We have helped a lot of missions 1-1 in the past, so it's not a big deal to answer questions or add patches for unsupported corner cases we didn't think of.
