### ISSUE TITLE
Sparse packet definitions with array fields are not assigned bit_offset

### ISSUE THREAD

**Issue by gfireman** [CCSDSPy/ccsdspy#97]
Array fields in a FixedLength packet definition are not assigned bit_offset.  When not all fields in the packet are defined, this has the effect of reading data starting with the previously-defined end of field instead of the requested position.

**Comment by gfireman** [comment]
Corrected with #99 [21c1dfc](https://github.com/CCSDSPy/ccsdspy/commit/21c1dfc6cbdf4ea6ae0cd3ea04dc7de271fee542)

**Comment by ddasilva** [comment]
Addressed in PR https://github.com/CCSDSPy/ccsdspy/pull/99
